apiVersion: v1
kind: Pod
metadata:
  name: yadav
spec:
  containers:
    - name: moosapet
      image: nginx
      env:
        - name: URL
          value: "avinash.guruka@gmail.com"
        - name: AVI
          value: "Guruka-Avinash-Yadav"