#apiVersion: v1
#kind: Pod
#metadata:
#  name: yadav
#spec:
#  containers:
#    - name: moosapet
#      image: nginx
#      env:
#        - name: URL
#          value: "avinash.guruka@gmail.com"
#        - name: AVI
#          value: "Guruka-Avinash-Yadav"

# if you have to pass multiple(above there are only 2) env variable  to a container, instead of having them all one by one under env, we can use "ConfigMaps"

apiVersion: v1
kind: Pod
metadata:
  name: manjula
spec:
  containers:
    - name: anusha
      image: mongo
      envFrom:
        - configMapRef:
            name: config-map



apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  URL: avinash.guruka@gmail.com
  AVI: Guruka-Avinash-Yadav