apiVersion: v1
kind: Secret
metadata:
  name: yadav
data:
  facebookPass: avinash@123
  whatsappPass: avinash@321
  instagramPass: avinash@456

apiVersion: v1
kind: Pod
metadata:
  name: avinash
spec:
  containers:
    - name: srinivas
      image: nginx
    - name: manjula
      image: tomcat
      envFrom:
        - SecretRef:
            name: yadav