apiVersion: v1
kind: Secret
metadata:
  name: yadav
data:
  facebookPass: YXZpbmFzaDEyMw==
  whatsappPass: YXZpbmFzaEAzMjE=
  instagramPass: YXZpbmFzaEA0NTY=
---
apiVersion: v1
kind: Pod
metadata:
  name: avinash
spec:
  containers:
    - name: srinivas
      image: nginx
    - name: manjula
      image: tomcat
      envFrom:
        - secretRef:
            name: yadav
            secret:
              secretName: facebookPass


#the above secrets gets attached only to the container based image:tomcat(container name: manjula) and not to continaer based image:nginx